name: backend-lambda-deploy-dev

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print AWS Credentials
        run: |
          echo "Trigger serveless Repo"
