name: test

on:
  push:
    branches:
      - dev
    paths:
      - .github/workflows/test.yml
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print AWS Credentials
        run: |
          echo "Trigger serverless Repo"
          echo "BRANCH : ${{ github.ref_name }}"
        
