name: test

on:
  push:
    branches:
      - dev
    paths:
      - .github/workflows/test.yml
  
jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
      - name: Print AWS Credentials
        run: |
          echo "Trigger serverless Repo"
          echo "BRANCH : ${{ github.ref_name }}"
          echo "AWS KEY : ${{ secrets.AWS_KEY }}"
          echo "AWS KEY 2 : ${{ vars.AWS_KEY2}}"
        
