name: test

on:
  push:
    branches:
      - dev
    paths:
      - folder1/**
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print AWS Credentials
        run: echo "Trigger serverless Repo"
